### PR TITLE
Feature/auth pages

### PR DESCRIPTION
**Pull request by MarwanBz**

### CODE REVIEW

**Review by fakhraldeen18 — APPROVED** [review]

**Comment by fakhraldeen18** [comment]
@MarwanBz you need to add some padding between the text file and the span of the error message 
Screenshot 2024-12-28 225718

**Comment by fakhraldeen18** [comment]
@MarwanBz  the validation of confirming the password doesn't work, maybe its work but the error message did not appear
image

**Comment by fakhraldeen18** [comment]
@MarwanBz the validation doesn't wok 


image

**Comment by MarwanBz** [comment]
@fakhraldeen18 
 I created #22  #21 #20 
these issues to fix them

thanks

**Pull request merged**
